# permissions for end users to edit falconimageanalyzers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: go-v4
    app.kubernetes.io/managed-by: kustomize
  name: falcon-falconimageanalyzer-editor-role
rules:
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconimageanalyzers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconimageanalyzers/status
  verbs:
  - get
