# permissions for end users to edit falconadmissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: go-v4
    app.kubernetes.io/managed-by: kustomize
  name: falcon-falconadmission-editor-role
rules:
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconadmissions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconadmissions/status
  verbs:
  - get
