---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-falcon-crowdstrike-com-v1alpha1-falconadmission
  failurePolicy: Fail
  name: vfalconadmission-v1alpha1.kb.io
  rules:
  - apiGroups:
    - falcon.crowdstrike.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - falconadmissions
  sideEffects: None
