# permissions for end users to edit falconoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: falcon-operator
    app.kubernetes.io/managed-by: kustomize
  name: falcon-FalconOperator-editor-role
rules:
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falconoperators/status
  verbs:
  - get
