apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "falcon-operator.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
    crowdstrike.com/component: manager
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: controller-manager
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: deployment
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  {{- include "falcon-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "falcon-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "falcon-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
                - ppc64le
                - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - args: {{- toYaml .Values.controllerManager.manager.args | nindent 8 }}
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          value: {{ quote .Values.controllerManager.manager.env.watchNamespace }}
        - name: OPERATOR_NAME
          value: {{ quote .Values.controllerManager.manager.env.operatorName }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext
          | nindent 10 }}
      securityContext: {{- toYaml .Values.controllerManager.podSecurityContext | nindent
        8 }}
      serviceAccountName: {{ include "falcon-operator.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
