apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "falcon-operator.fullname" . }}-falcon-FalconDeployment-viewer-role
  labels:
  {{- include "falcon-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falcondeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - falcon.crowdstrike.com
  resources:
  - falcondeployments/status
  verbs:
  - get
