apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "falcon-operator.fullname" . }}-leader-election-role
  labels:
    crowdstrike.com/component: rbac
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: leader-election-role
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: role
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  {{- include "falcon-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "falcon-operator.fullname" . }}-leader-election-rolebinding
  labels:
    crowdstrike.com/component: rbac
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: leader-election-rolebinding
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: rolebinding
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  {{- include "falcon-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "falcon-operator.fullname" . }}-leader-election-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "falcon-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
