apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "falcon-operator.fullname" . }}-node-sensor-role
  labels:
    crowdstrike.com/component: rbac
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: node-sensor-role
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: clusterrole
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  {{- include "falcon-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  - cronjobs
  - daemonsets
  - deployments
  - ingresses
  - jobs
  - nodes
  - persistentvolumes
  - pods
  - replicasets
  - services
  verbs:
  - get
  - list
  - watch
